In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("files\data_cts_violent_and_sexual_crime(data_cts_violent_and_sexual_cri).csv", encoding="latin1", delimiter=";", header = 2)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\adria\AppData\Local\Temp\ipykernel_25552\262079912.py:1: SyntaxWarning: invalid escape sequence '\d'
  df = pd.read_csv("files\data_cts_violent_and_sexual_crime(data_cts_violent_and_sexual_cri).csv", encoding="latin1", delimiter=";", header = 2)

In [3]:
df.head(5)

,Iso3_code,Country,Region,Subregion,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE,Source
0,AZE,Azerbaijan,Asia,Western Asia,Violent offences,by type of offence,Serious assault,Total,Total,2003,Counts,155,CTS
1,BEL,Belgium,Europe,Western Europe,Violent offences,by type of offence,Serious assault,Total,Total,2003,Counts,61959,CTS
2,BGR,Bulgaria,Europe,Eastern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2003,Counts,3806,CTS
3,BHR,Bahrain,Asia,Western Asia,Violent offences,by type of offence,Serious assault,Total,Total,2003,Counts,2701,CTS
4,BLR,Belarus,Europe,Eastern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2003,Counts,4032,CTS

In [4]:
df.columns

Index(['Iso3_code', 'Country', 'Region', 'Subregion', 'Indicator', 'Dimension',
       'Category', 'Sex', 'Age', 'Year', 'Unit of measurement', 'VALUE',
       'Source'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26114 entries, 0 to 26113
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Iso3_code            26114 non-null  object
 1   Country              26114 non-null  object
 2   Region               26114 non-null  object
 3   Subregion            26114 non-null  object
 4   Indicator            26114 non-null  object
 5   Dimension            26114 non-null  object
 6   Category             26114 non-null  object
 7   Sex                  26114 non-null  object
 8   Age                  26114 non-null  object
 9   Year                 26114 non-null  int64
 10  Unit of measurement  26114 non-null  object
 11  VALUE                26114 non-null  object
 12  Source               26114 non-null  object
dtypes: int64(1), object(12)
memory usage: 2.6+ MB

In [6]:
df['Unit of measurement'].unique()

array(['Counts', 'Rate per 100,000 population'], dtype=object)

In [7]:
df['Country'].unique()

array(['Azerbaijan', 'Belgium', 'Bulgaria', 'Bahrain', 'Belarus',
       'Bermuda', 'Brunei Darussalam', 'Canada', 'Switzerland',
       'Cameroon', 'Cyprus', 'Germany', 'Denmark', 'Algeria', 'Ecuador',
       'Finland', 'France', 'United Kingdom (England and Wales)',
       'United Kingdom (Northern Ireland)', 'United Kingdom (Scotland)',
       'Greece', 'China, Hong Kong Special Administrative Region',
       'Croatia', 'Hungary', 'Ireland', 'Japan', 'Kyrgyzstan',
       'Liechtenstein', 'Sri Lanka', 'Lithuania', 'Latvia', 'Morocco',
       'Monaco', 'Montenegro', 'Mongolia', 'Mauritius',
       'Netherlands (Kingdom of the)', 'Norway', 'Portugal',
       'State of Palestine', 'Qatar', 'Romania', 'Singapore',
       'Sao Tome and Principe', 'Slovakia', 'Slovenia', 'Sweden',
       'Eswatini', 'Syrian Arab Republic', 'TÃ¼rkiye', 'Uganda', 'Ukraine',
       'United States of America', 'Zimbabwe', 'Armenia', 'Austria',
       'Barbados', 'Colombia', 'Czechia', 'Georgia', 'Guatemala', 'India',
       'Israel', 'Italy', 'Kuwait', 'Mexico', 'Mozambique', 'Peru',
       'Russian Federation', 'Solomon Islands', 'Trinidad and Tobago',
       'Saint Vincent and the Grenadines', 'Albania',
       'United Arab Emirates', 'Argentina', 'Bangladesh',
       'Bosnia and Herzegovina', 'Bolivia (Plurinational State of)',
       'Spain', 'Estonia', 'Guinea', 'Grenada', 'Jordan', 'Kenya',
       'Republic of Moldova', 'Malaysia', 'Nicaragua', 'Nepal',
       'New Zealand', 'Paraguay', 'Senegal', 'El Salvador', 'Serbia',
       'Thailand', 'Turkmenistan', 'Belize', 'Brazil', 'Chile',
       'Costa Rica', 'Egypt', 'Iceland', 'Kazakhstan',
       'Republic of Korea', 'Luxembourg', 'North Macedonia', 'Panama',
       'Tajikistan', 'Uruguay', 'Andorra', 'CÃ´te d\x92Ivoire', 'Lesotho',
       'Nigeria', 'Oman', 'Sierra Leone', 'Australia', 'Burundi',
       'Indonesia', 'Iraq (Central Iraq)', 'Lebanon',
       'China, Macao Special Administrative Region', 'Malta',
       'Puerto Rico', 'Rwanda', 'Kosovo under UNSCR 1244', 'Bahamas',
       'Botswana', 'Saint Kitts and Nevis', 'Myanmar', 'Poland',
       'Holy See', 'Yemen', 'Cabo Verde', 'Guyana', 'Jamaica',
       'Madagascar', 'Pakistan', 'Honduras', 'Dominican Republic',
       'Guinea-Bissau', 'Bhutan', 'Dominica', 'Maldives', 'Suriname',
       'United Republic of Tanzania', 'Uzbekistan', 'South Africa',
       'Antigua and Barbuda', 'Saudi Arabia',
       'Venezuela (Bolivarian Republic of)', 'Philippines', 'Benin',
       'Saint Lucia', 'Ghana', 'Haiti', 'Namibia', 'Sudan', 'Timor-Leste'],
      dtype=object)

In [8]:
df['Year'].unique()

array([2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022], dtype=int64)

In [9]:
df_19_22 = df[df['Year'].between(2019,2022,inclusive='both')]

In [10]:
df_19_22.to_csv('files/df_19_22.csv')

In [11]:
df_19_22.head(20)

,Iso3_code,Country,Region,Subregion,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE,Source
1591,ALB,Albania,Europe,Southern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,158,CTS
1592,AND,Andorra,Europe,Southern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,250,CTS
1593,ARE,United Arab Emirates,Asia,Western Asia,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,192,CTS
1594,ARG,Argentina,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,143697,CTS
1595,ARM,Armenia,Asia,Western Asia,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,210,CTS
1596,ATG,Antigua and Barbuda,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,3,CTS
1597,AUS,Australia,Oceania,Australia and New Zealand,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,72384,CTS
1598,AUT,Austria,Europe,Western Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,3835,CTS
1599,AZE,Azerbaijan,Asia,Western Asia,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,318,CTS
1600,BEL,Belgium,Europe,Western Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,64022,CTS
1601,BGR,Bulgaria,Europe,Eastern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,2768,CTS
1602,BHS,Bahamas,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,4035,CTS
1603,BIH,Bosnia and Herzegovina,Europe,Southern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,725,CTS
1604,BLR,Belarus,Europe,Eastern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,719,CTS
1605,BLZ,Belize,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,1851,CTS/MoI
1606,BOL,Bolivia (Plurinational State of),Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,8211,CTS
1607,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,602782,CTS/DATASUS
1608,BRB,Barbados,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,770,CTS
1609,BTN,Bhutan,Asia,Southern Asia,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,895,CTS
1610,CAN,Canada,Americas,Northern America,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,63677,CTS

In [12]:
df_19_22['Dimension'].unique()

array(['by type of offence', 'by relationship to perpetrator'],
      dtype=object)

In [13]:
df_19_22[(df_19_22['Country'] == 'Brazil') | (df_19_22['Country'] == 'United States of America')]['VALUE'].nunique()

36

In [14]:
df_19_22[(df_19_22['Country'] == 'Brazil')]['VALUE'].nunique()

16

In [15]:
df_19_22[(df_19_22['Country'] == 'Brazil') | (df_19_22['Country'] == 'United States of America')].sample(20)

,Iso3_code,Country,Region,Subregion,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE,Source
1607,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,602782,CTS/DATASUS
16541,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Kidnapping,Total,Total,2019,"Rate per 100,000 population","0,254033756",CTS/DATASUS
20277,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Sexual violence: Rape,Total,Total,2019,"Rate per 100,000 population","22,49756942",CTS/DATASUS
20637,USA,United States of America,Americas,Northern America,Violent offences,by type of offence,Sexual violence: Rape,Total,Total,2022,"Rate per 100,000 population","41,8238966",CTS
7483,USA,United States of America,Americas,Northern America,Violent offences,by type of offence,Sexual violence: Rape,Total,Total,2021,Counts,"140776,0081",CTS
20363,USA,United States of America,Americas,Northern America,Violent offences,by type of offence,Sexual violence: Rape,Total,Total,2019,"Rate per 100,000 population","42,8404346",CTS
7306,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Sexual violence: Rape,Total,Total,2020,Counts,47701,CTS/DATASUS
16866,USA,United States of America,Americas,Northern America,Violent offences,by type of offence,Kidnapping,Total,Total,2022,"Rate per 100,000 population","15,50179496",CTS
14782,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2020,"Rate per 100,000 population","216,766891",CTS/DATASUS
21278,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Sexual violence: Sexual assault,Total,Total,2020,"Rate per 100,000 population","4,116394063",CTS/DATASUS
7290,USA,United States of America,Americas,Northern America,Violent offences,by type of offence,Sexual violence: Rape,Total,Total,2019,Counts,143224,CTS
1709,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2020,Counts,462139,CTS/DATASUS
8205,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Sexual violence: Sexual assault,Total,Total,2020,Counts,8776,CTS/DATASUS
8118,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Sexual violence: Sexual assault,Total,Total,2019,Counts,7413,CTS/DATASUS
1792,USA,United States of America,Americas,Northern America,Violent offences,by type of offence,Serious assault,Total,Total,2020,Counts,921505,CTS
14865,USA,United States of America,Americas,Northern America,Violent offences,by type of offence,Serious assault,Total,Total,2020,"Rate per 100,000 population","274,3047874",CTS
1692,USA,United States of America,Americas,Northern America,Violent offences,by type of offence,Serious assault,Total,Total,2019,Counts,822017,CTS
15047,USA,United States of America,Americas,Northern America,Violent offences,by type of offence,Serious assault,Total,Total,2022,"Rate per 100,000 population","280,5857109",CTS
3559,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Kidnapping,Total,Total,2020,Counts,4390,CTS/DATASUS
16789,USA,United States of America,Americas,Northern America,Violent offences,by type of offence,Kidnapping,Total,Total,2021,"Rate per 100,000 population","16,81066689",CTS

In [16]:
df_rate = df_19_22[df_19_22['Unit of measurement'] == 'Rate per 100,000 population']

In [17]:
df_rate.to_csv('files/df_rate.csv')

In [18]:
df_rate.head(20)

,Iso3_code,Country,Region,Subregion,Indicator,Dimension,Category,Sex,Age,Year,Unit of measurement,VALUE,Source
14664,ALB,Albania,Europe,Southern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","5,497786271",CTS
14665,AND,Andorra,Europe,Southern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","327,4694471",CTS
14666,ARE,United Arab Emirates,Asia,Western Asia,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","2,084315558",CTS
14667,ARG,Argentina,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","321,1427647",CTS
14668,ARM,Armenia,Asia,Western Asia,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","7,445219141",CTS
14669,ATG,Antigua and Barbuda,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","3,256745534",CTS
14670,AUS,Australia,Oceania,Australia and New Zealand,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","285,4577226",CTS
14671,AUT,Austria,Europe,Western Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","43,18722874",CTS
14672,AZE,Azerbaijan,Asia,Western Asia,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","3,107668093",CTS
14673,BEL,Belgium,Europe,Western Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","556,2019181",CTS
14674,BGR,Bulgaria,Europe,Eastern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","39,24831536",CTS
14675,BHS,Bahamas,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","997,3872656",CTS
14676,BIH,Bosnia and Herzegovina,Europe,Southern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","21,57280957",CTS
14677,BLR,Belarus,Europe,Eastern Europe,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","7,432315023",CTS
14678,BLZ,Belize,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","475,7192973",CTS/MoI
14679,BOL,Bolivia (Plurinational State of),Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","69,71877716",CTS
14680,BRA,Brazil,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","284,6226313",CTS/DATASUS
14681,BRB,Barbados,Americas,Latin America and the Caribbean,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","274,8238183",CTS
14682,BTN,Bhutan,Asia,Southern Asia,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","116,6186076",CTS
14683,CAN,Canada,Americas,Northern America,Violent offences,by type of offence,Serious assault,Total,Total,2019,"Rate per 100,000 population","169,7031268",CTS

In [19]:
df_rate['Sex'].unique()

array(['Total', 'Male', 'Female'], dtype=object)

In [20]:
df_rate['Category'].unique()

array(['Serious assault', 'Kidnapping', 'Sexual violence',
       'Sexual violence: Rape', 'Sexual violence: Sexual assault',
       'Sexual violence: Other acts of sexual violence',
       'Sexual Exploitation', 'Intimate partner or family member',
       'Other Perpetrator known to the victim',
       'Perpetrator unknown to the victim',
       'Relationship to perpetrator is not known',
       'Acts intended to induce fear or emotional distress',
       'Acts intended to induce fear or emotional distress: Cyber-related'],
      dtype=object)

In [21]:
df_rate['Indicator'].unique()

array(['Violent offences', 'Victims of serious assault',
       'Victims of sexual violence'], dtype=object)

In [22]:
df.columns

Index(['Iso3_code', 'Country', 'Region', 'Subregion', 'Indicator', 'Dimension',
       'Category', 'Sex', 'Age', 'Year', 'Unit of measurement', 'VALUE',
       'Source'],
      dtype='object')